/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { Joetroller, JoetrollerInterface } from "../Joetroller";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "jTokenAddress",
        type: "address",
      },
    ],
    name: "isMarketListed",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class Joetroller__factory {
  static readonly abi = _abi;
  static createInterface(): JoetrollerInterface {
    return new utils.Interface(_abi) as JoetrollerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Joetroller {
    return new Contract(address, _abi, signerOrProvider) as Joetroller;
  }
}
