/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "ERC3156FlashBorrowerInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC3156FlashBorrowerInterface__factory>;
    getContractFactory(
      name: "ERC3156FlashLenderInterface",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC3156FlashLenderInterface__factory>;
    getContractFactory(
      name: "IERC20Joe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Joe__factory>;
    getContractFactory(
      name: "IJoeFactory",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IJoeFactory__factory>;
    getContractFactory(
      name: "IJoePair",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IJoePair__factory>;
    getContractFactory(
      name: "IJoeRouter01",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IJoeRouter01__factory>;
    getContractFactory(
      name: "IJoeRouter02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IJoeRouter02__factory>;
    getContractFactory(
      name: "IWAVAX",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWAVAX__factory>;
    getContractFactory(
      name: "JoeRouter02",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JoeRouter02__factory>;
    getContractFactory(
      name: "Joetroller",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Joetroller__factory>;
    getContractFactory(
      name: "JToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.JToken__factory>;
    getContractFactory(
      name: "LiquidatorJoe",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiquidatorJoe__factory>;

    getContractAt(
      name: "ERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "ERC3156FlashBorrowerInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC3156FlashBorrowerInterface>;
    getContractAt(
      name: "ERC3156FlashLenderInterface",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC3156FlashLenderInterface>;
    getContractAt(
      name: "IERC20Joe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Joe>;
    getContractAt(
      name: "IJoeFactory",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IJoeFactory>;
    getContractAt(
      name: "IJoePair",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IJoePair>;
    getContractAt(
      name: "IJoeRouter01",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IJoeRouter01>;
    getContractAt(
      name: "IJoeRouter02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IJoeRouter02>;
    getContractAt(
      name: "IWAVAX",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IWAVAX>;
    getContractAt(
      name: "JoeRouter02",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JoeRouter02>;
    getContractAt(
      name: "Joetroller",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Joetroller>;
    getContractAt(
      name: "JToken",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.JToken>;
    getContractAt(
      name: "LiquidatorJoe",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.LiquidatorJoe>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
