/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface JoetrollerInterface extends utils.Interface {
  contractName: "Joetroller";
  functions: {
    "isMarketListed(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isMarketListed",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "isMarketListed",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Joetroller extends BaseContract {
  contractName: "Joetroller";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: JoetrollerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isMarketListed(
      jTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  isMarketListed(
    jTokenAddress: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    isMarketListed(
      jTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isMarketListed(
      jTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isMarketListed(
      jTokenAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
